"""Добавлен unique к user email

Revision ID: 457cf2d92681
Revises: 028b5ecd3d69
Create Date: 2019-06-20 17:43:38.786182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457cf2d92681'
down_revision = '028b5ecd3d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
