"""empty message

Revision ID: 5f2edfe5e5c6
Revises: aee53a45b05c
Create Date: 2019-07-11 11:04:07.339111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2edfe5e5c6'
down_revision = 'aee53a45b05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(op.f('event_creator_id'), 'user', ['event_creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('event_creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
