"""user creator

Revision ID: abe40618258d
Revises: 1a09fa83d08f
Create Date: 2019-07-06 11:48:31.552311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe40618258d'
down_revision = '1a09fa83d08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_creator_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date_finish',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_foreign_key(op.f('event_creator_id'), 'user', ['event_creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('date_finish',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('event_creator_id')

    # ### end Alembic commands ###
