"""empty message

Revision ID: f296dd4bae73
Revises: 1a09fa83d08f
Create Date: 2019-06-29 13:06:24.120603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f296dd4bae73'
down_revision = '1a09fa83d08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['event_creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_creator_id')

    # ### end Alembic commands ###
